/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GamingAssetNFT__factory } from "./GamingAssetNFT__factory";
export { IGameAsset__factory } from "./IGameAsset__factory";
