/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace GamePaymentFacet {
  export type MatchStruct = {
    player1: AddressLike;
    player2: AddressLike;
    agentId1: BigNumberish;
    agentId2: BigNumberish;
    totalEscrowed: BigNumberish;
    settled: boolean;
    winner: AddressLike;
    startTime: BigNumberish;
    minDuration: BigNumberish;
  };

  export type MatchStructOutput = [
    player1: string,
    player2: string,
    agentId1: bigint,
    agentId2: bigint,
    totalEscrowed: bigint,
    settled: boolean,
    winner: string,
    startTime: bigint,
    minDuration: bigint
  ] & {
    player1: string;
    player2: string;
    agentId1: bigint;
    agentId2: bigint;
    totalEscrowed: bigint;
    settled: boolean;
    winner: string;
    startTime: bigint;
    minDuration: bigint;
  };
}

export interface GamePaymentFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "burnBpsOfProtocol"
      | "entryFeeSALT"
      | "game_commitCoinFlip"
      | "game_commitShipPlacement"
      | "game_createAIVsAIMatch"
      | "game_emergencyWithdraw"
      | "game_getAgentStats"
      | "game_getCurrentEntryFeeSALT"
      | "game_getEntryFee"
      | "game_getFeeDistributor"
      | "game_getGameServer"
      | "game_getMatch"
      | "game_getNextMatchId"
      | "game_getPlayerStats"
      | "game_getSaltToken"
      | "game_getSettlementDelay"
      | "game_getTwapPrice"
      | "game_initialize"
      | "game_payToEnterMatch"
      | "game_recordAgentGameResult"
      | "game_recordGameResult"
      | "game_registerFreeLoadout"
      | "game_registerLoadoutForAgent"
      | "game_revealCoinFlipAndCreateMatch"
      | "game_revealShipPlacement"
      | "game_setEntryFeeSALT"
      | "game_setFeeDistributor"
      | "game_setGameServer"
      | "game_setMaxPriceDeviationBps"
      | "game_setPriceFeed"
      | "game_setProtocolFeeBps"
      | "game_setSettlementDelay"
      | "game_setTargetEntryUSD"
      | "game_setTwapWindow"
      | "game_settleMatch"
      | "game_updatePriceHistory"
      | "game_verifyShipPlacementZK"
      | "maxPriceDeviationBps"
      | "nextMatchId"
      | "priceFeed"
      | "priceHistory"
      | "priceHistoryIndex"
      | "protocolFeeBps"
      | "targetEntryUSD"
      | "twapWindow"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MatchCreated" | "MatchSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "burnBpsOfProtocol",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entryFeeSALT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "game_commitCoinFlip",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "game_commitShipPlacement",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "game_createAIVsAIMatch",
    values: [BigNumberish, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "game_emergencyWithdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "game_getAgentStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "game_getCurrentEntryFeeSALT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "game_getEntryFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "game_getFeeDistributor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "game_getGameServer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "game_getMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "game_getNextMatchId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "game_getPlayerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "game_getSaltToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "game_getSettlementDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "game_getTwapPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "game_initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "game_payToEnterMatch",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "game_recordAgentGameResult",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "game_recordGameResult",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "game_registerFreeLoadout",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "game_registerLoadoutForAgent",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "game_revealCoinFlipAndCreateMatch",
    values: [BigNumberish, AddressLike, BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "game_revealShipPlacement",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "game_setEntryFeeSALT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "game_setFeeDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "game_setGameServer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "game_setMaxPriceDeviationBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "game_setPriceFeed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "game_setProtocolFeeBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "game_setSettlementDelay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "game_setTargetEntryUSD",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "game_setTwapWindow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "game_settleMatch",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "game_updatePriceHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "game_verifyShipPlacementZK",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxPriceDeviationBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextMatchId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "priceFeed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "priceHistoryIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetEntryUSD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "twapWindow",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "burnBpsOfProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entryFeeSALT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_commitCoinFlip",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_commitShipPlacement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_createAIVsAIMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_getAgentStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_getCurrentEntryFeeSALT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_getEntryFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_getFeeDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_getGameServer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_getMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_getNextMatchId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_getPlayerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_getSaltToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_getSettlementDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_getTwapPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_initialize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_payToEnterMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_recordAgentGameResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_recordGameResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_registerFreeLoadout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_registerLoadoutForAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_revealCoinFlipAndCreateMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_revealShipPlacement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_setEntryFeeSALT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_setFeeDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_setGameServer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_setMaxPriceDeviationBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_setPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_setProtocolFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_setSettlementDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_setTargetEntryUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_setTwapWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_settleMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_updatePriceHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "game_verifyShipPlacementZK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxPriceDeviationBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextMatchId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "priceFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceHistoryIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetEntryUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "twapWindow", data: BytesLike): Result;
}

export namespace MatchCreatedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    player1: AddressLike,
    player2: AddressLike,
    agentId1: BigNumberish,
    agentId2: BigNumberish,
    entryFee: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    player1: string,
    player2: string,
    agentId1: bigint,
    agentId2: bigint,
    entryFee: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    player1: string;
    player2: string;
    agentId1: bigint;
    agentId2: bigint;
    entryFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchSettledEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    winner: AddressLike,
    agentIdWinner: BigNumberish,
    payout: BigNumberish,
    protocolFee: BigNumberish,
    burned: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    winner: string,
    agentIdWinner: bigint,
    payout: bigint,
    protocolFee: bigint,
    burned: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    winner: string;
    agentIdWinner: bigint;
    payout: bigint;
    protocolFee: bigint;
    burned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GamePaymentFacet extends BaseContract {
  connect(runner?: ContractRunner | null): GamePaymentFacet;
  waitForDeployment(): Promise<this>;

  interface: GamePaymentFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  burnBpsOfProtocol: TypedContractMethod<[], [bigint], "view">;

  entryFeeSALT: TypedContractMethod<[], [bigint], "view">;

  game_commitCoinFlip: TypedContractMethod<
    [matchId: BigNumberish, commitment: BytesLike],
    [void],
    "nonpayable"
  >;

  game_commitShipPlacement: TypedContractMethod<
    [matchId: BigNumberish, commitment: BytesLike],
    [void],
    "nonpayable"
  >;

  game_createAIVsAIMatch: TypedContractMethod<
    [
      matchId: BigNumberish,
      aiAgent1: AddressLike,
      aiAgent2: AddressLike,
      agentId1: BigNumberish,
      agentId2: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  game_emergencyWithdraw: TypedContractMethod<
    [to: AddressLike],
    [void],
    "nonpayable"
  >;

  game_getAgentStats: TypedContractMethod<
    [agentId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        _wins: bigint;
        _losses: bigint;
        _games: bigint;
      }
    ],
    "view"
  >;

  game_getCurrentEntryFeeSALT: TypedContractMethod<[], [bigint], "view">;

  game_getEntryFee: TypedContractMethod<[], [bigint], "view">;

  game_getFeeDistributor: TypedContractMethod<[], [string], "view">;

  game_getGameServer: TypedContractMethod<[], [string], "view">;

  game_getMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [GamePaymentFacet.MatchStructOutput],
    "view"
  >;

  game_getNextMatchId: TypedContractMethod<[], [bigint], "view">;

  game_getPlayerStats: TypedContractMethod<
    [player: AddressLike],
    [
      [bigint, bigint, bigint] & {
        _wins: bigint;
        _losses: bigint;
        _games: bigint;
      }
    ],
    "view"
  >;

  game_getSaltToken: TypedContractMethod<[], [string], "view">;

  game_getSettlementDelay: TypedContractMethod<[], [bigint], "view">;

  game_getTwapPrice: TypedContractMethod<[], [bigint], "view">;

  game_initialize: TypedContractMethod<
    [_saltToken: AddressLike],
    [void],
    "nonpayable"
  >;

  game_payToEnterMatch: TypedContractMethod<
    [matchId: BigNumberish, opponent: AddressLike],
    [void],
    "nonpayable"
  >;

  game_recordAgentGameResult: TypedContractMethod<
    [winnerAgentId: BigNumberish, loserAgentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  game_recordGameResult: TypedContractMethod<
    [winner: AddressLike, loser: AddressLike],
    [void],
    "nonpayable"
  >;

  game_registerFreeLoadout: TypedContractMethod<
    [placementHash: BytesLike],
    [void],
    "nonpayable"
  >;

  game_registerLoadoutForAgent: TypedContractMethod<
    [agentId: BigNumberish, placementHash: BytesLike],
    [void],
    "nonpayable"
  >;

  game_revealCoinFlipAndCreateMatch: TypedContractMethod<
    [
      matchId: BigNumberish,
      arg1: AddressLike,
      salt: BytesLike,
      firstMover: boolean
    ],
    [void],
    "nonpayable"
  >;

  game_revealShipPlacement: TypedContractMethod<
    [matchId: BigNumberish, placementData: BytesLike, salt: BytesLike],
    [void],
    "nonpayable"
  >;

  game_setEntryFeeSALT: TypedContractMethod<
    [_newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  game_setFeeDistributor: TypedContractMethod<
    [_distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  game_setGameServer: TypedContractMethod<
    [_server: AddressLike],
    [void],
    "nonpayable"
  >;

  game_setMaxPriceDeviationBps: TypedContractMethod<
    [_bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  game_setPriceFeed: TypedContractMethod<
    [_feed: AddressLike],
    [void],
    "nonpayable"
  >;

  game_setProtocolFeeBps: TypedContractMethod<
    [_bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  game_setSettlementDelay: TypedContractMethod<
    [_delay: BigNumberish],
    [void],
    "nonpayable"
  >;

  game_setTargetEntryUSD: TypedContractMethod<
    [_usd: BigNumberish],
    [void],
    "nonpayable"
  >;

  game_setTwapWindow: TypedContractMethod<
    [_window: BigNumberish],
    [void],
    "nonpayable"
  >;

  game_settleMatch: TypedContractMethod<
    [
      matchId: BigNumberish,
      winner: AddressLike,
      nonce: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  game_updatePriceHistory: TypedContractMethod<
    [currentPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  game_verifyShipPlacementZK: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: BytesLike],
    [boolean],
    "view"
  >;

  maxPriceDeviationBps: TypedContractMethod<[], [bigint], "view">;

  nextMatchId: TypedContractMethod<[], [bigint], "view">;

  priceFeed: TypedContractMethod<[], [string], "view">;

  priceHistory: TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, bigint] & { price: bigint; timestamp: bigint }],
    "view"
  >;

  priceHistoryIndex: TypedContractMethod<[], [bigint], "view">;

  protocolFeeBps: TypedContractMethod<[], [bigint], "view">;

  targetEntryUSD: TypedContractMethod<[], [bigint], "view">;

  twapWindow: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "burnBpsOfProtocol"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "entryFeeSALT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "game_commitCoinFlip"
  ): TypedContractMethod<
    [matchId: BigNumberish, commitment: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "game_commitShipPlacement"
  ): TypedContractMethod<
    [matchId: BigNumberish, commitment: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "game_createAIVsAIMatch"
  ): TypedContractMethod<
    [
      matchId: BigNumberish,
      aiAgent1: AddressLike,
      aiAgent2: AddressLike,
      agentId1: BigNumberish,
      agentId2: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "game_emergencyWithdraw"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "game_getAgentStats"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        _wins: bigint;
        _losses: bigint;
        _games: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "game_getCurrentEntryFeeSALT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "game_getEntryFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "game_getFeeDistributor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "game_getGameServer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "game_getMatch"
  ): TypedContractMethod<
    [matchId: BigNumberish],
    [GamePaymentFacet.MatchStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "game_getNextMatchId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "game_getPlayerStats"
  ): TypedContractMethod<
    [player: AddressLike],
    [
      [bigint, bigint, bigint] & {
        _wins: bigint;
        _losses: bigint;
        _games: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "game_getSaltToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "game_getSettlementDelay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "game_getTwapPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "game_initialize"
  ): TypedContractMethod<[_saltToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "game_payToEnterMatch"
  ): TypedContractMethod<
    [matchId: BigNumberish, opponent: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "game_recordAgentGameResult"
  ): TypedContractMethod<
    [winnerAgentId: BigNumberish, loserAgentId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "game_recordGameResult"
  ): TypedContractMethod<
    [winner: AddressLike, loser: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "game_registerFreeLoadout"
  ): TypedContractMethod<[placementHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "game_registerLoadoutForAgent"
  ): TypedContractMethod<
    [agentId: BigNumberish, placementHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "game_revealCoinFlipAndCreateMatch"
  ): TypedContractMethod<
    [
      matchId: BigNumberish,
      arg1: AddressLike,
      salt: BytesLike,
      firstMover: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "game_revealShipPlacement"
  ): TypedContractMethod<
    [matchId: BigNumberish, placementData: BytesLike, salt: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "game_setEntryFeeSALT"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "game_setFeeDistributor"
  ): TypedContractMethod<[_distributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "game_setGameServer"
  ): TypedContractMethod<[_server: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "game_setMaxPriceDeviationBps"
  ): TypedContractMethod<[_bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "game_setPriceFeed"
  ): TypedContractMethod<[_feed: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "game_setProtocolFeeBps"
  ): TypedContractMethod<[_bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "game_setSettlementDelay"
  ): TypedContractMethod<[_delay: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "game_setTargetEntryUSD"
  ): TypedContractMethod<[_usd: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "game_setTwapWindow"
  ): TypedContractMethod<[_window: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "game_settleMatch"
  ): TypedContractMethod<
    [
      matchId: BigNumberish,
      winner: AddressLike,
      nonce: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "game_updatePriceHistory"
  ): TypedContractMethod<[currentPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "game_verifyShipPlacementZK"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxPriceDeviationBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextMatchId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "priceFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, bigint] & { price: bigint; timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "priceHistoryIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "targetEntryUSD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "twapWindow"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "MatchCreated"
  ): TypedContractEvent<
    MatchCreatedEvent.InputTuple,
    MatchCreatedEvent.OutputTuple,
    MatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MatchSettled"
  ): TypedContractEvent<
    MatchSettledEvent.InputTuple,
    MatchSettledEvent.OutputTuple,
    MatchSettledEvent.OutputObject
  >;

  filters: {
    "MatchCreated(uint256,address,address,uint256,uint256,uint256)": TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;
    MatchCreated: TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;

    "MatchSettled(uint256,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      MatchSettledEvent.InputTuple,
      MatchSettledEvent.OutputTuple,
      MatchSettledEvent.OutputObject
    >;
    MatchSettled: TypedContractEvent<
      MatchSettledEvent.InputTuple,
      MatchSettledEvent.OutputTuple,
      MatchSettledEvent.OutputObject
    >;
  };
}
