/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AgentIdentityFacet } from "./AgentIdentityFacet";
export type { IAgentIdentity } from "./IAgentIdentity";
