/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAvABetting,
  IAvABettingInterface,
} from "../../../contracts/betting/IAvABetting";

const _abi = [
  {
    inputs: [],
    name: "ava_getGameServer",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ava_getSaltToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_gameServer",
        type: "address",
      },
    ],
    name: "ava_setGameServer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_salt",
        type: "address",
      },
    ],
    name: "ava_setSaltToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
    ],
    name: "betPools",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
    ],
    name: "betsSettled",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "winningAgentId",
        type: "uint256",
      },
    ],
    name: "claimWinnings",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "agentId1",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "agentId2",
        type: "uint256",
      },
    ],
    name: "getAvABettingInfo",
    outputs: [
      {
        internalType: "uint256",
        name: "totalPool",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "agent1Pool",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "agent2Pool",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "winningAgentId",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "settled",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getUserBet",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "agentId1",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "agentId2",
        type: "uint256",
      },
    ],
    name: "getUserBets",
    outputs: [
      {
        internalType: "uint256",
        name: "betOn1",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "betOn2",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
    ],
    name: "matchWinner",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "onAgentId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "placeBet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "winningAgentId",
        type: "uint256",
      },
    ],
    name: "settleAvABets",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAvABetting__factory {
  static readonly abi = _abi;
  static createInterface(): IAvABettingInterface {
    return new Interface(_abi) as IAvABettingInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAvABetting {
    return new Contract(address, _abi, runner) as unknown as IAvABetting;
  }
}
