/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AvABettingFacet__factory } from "./AvABettingFacet__factory";
export { IAvABetting__factory } from "./IAvABetting__factory";
