/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LibDiamond__factory } from "./LibDiamond__factory";
export { LibERC20__factory } from "./LibERC20__factory";
