/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AvABettingFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ava_getGameServer"
      | "ava_getSaltToken"
      | "ava_setGameServer"
      | "ava_setSaltToken"
      | "betPools"
      | "betsSettled"
      | "claimWinnings"
      | "getAvABettingInfo"
      | "getUserBet"
      | "getUserBets"
      | "matchTotalPool"
      | "matchWinner"
      | "placeBet"
      | "settleAvABets"
      | "userBets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AvABetsSettled" | "BetPlaced"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ava_getGameServer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ava_getSaltToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ava_setGameServer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ava_setSaltToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "betPools",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "betsSettled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimWinnings",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAvABettingInfo",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBet",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBets",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "matchTotalPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "matchWinner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleAvABets",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userBets",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ava_getGameServer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ava_getSaltToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ava_setGameServer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ava_setSaltToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "betPools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "betsSettled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvABettingInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUserBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchTotalPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settleAvABets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userBets", data: BytesLike): Result;
}

export namespace AvABetsSettledEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    winningAgentId: BigNumberish,
    totalPool: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    winningAgentId: bigint,
    totalPool: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    winningAgentId: bigint;
    totalPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    agentId: BigNumberish,
    better: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    agentId: bigint,
    better: string,
    amount: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    agentId: bigint;
    better: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AvABettingFacet extends BaseContract {
  connect(runner?: ContractRunner | null): AvABettingFacet;
  waitForDeployment(): Promise<this>;

  interface: AvABettingFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ava_getGameServer: TypedContractMethod<[], [string], "view">;

  ava_getSaltToken: TypedContractMethod<[], [string], "view">;

  ava_setGameServer: TypedContractMethod<
    [_gameServer: AddressLike],
    [void],
    "nonpayable"
  >;

  ava_setSaltToken: TypedContractMethod<
    [_salt: AddressLike],
    [void],
    "nonpayable"
  >;

  betPools: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  betsSettled: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  claimWinnings: TypedContractMethod<
    [matchId: BigNumberish, winningAgentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAvABettingInfo: TypedContractMethod<
    [matchId: BigNumberish, agentId1: BigNumberish, agentId2: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        totalPool: bigint;
        agent1Pool: bigint;
        agent2Pool: bigint;
        winningAgentId: bigint;
        settled: boolean;
      }
    ],
    "view"
  >;

  getUserBet: TypedContractMethod<
    [matchId: BigNumberish, agentId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  getUserBets: TypedContractMethod<
    [
      matchId: BigNumberish,
      user: AddressLike,
      agentId1: BigNumberish,
      agentId2: BigNumberish
    ],
    [[bigint, bigint] & { betOn1: bigint; betOn2: bigint }],
    "view"
  >;

  matchTotalPool: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  matchWinner: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  placeBet: TypedContractMethod<
    [matchId: BigNumberish, onAgentId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  settleAvABets: TypedContractMethod<
    [matchId: BigNumberish, winningAgentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  userBets: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ava_getGameServer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ava_getSaltToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ava_setGameServer"
  ): TypedContractMethod<[_gameServer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ava_setSaltToken"
  ): TypedContractMethod<[_salt: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "betPools"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "betsSettled"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "claimWinnings"
  ): TypedContractMethod<
    [matchId: BigNumberish, winningAgentId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAvABettingInfo"
  ): TypedContractMethod<
    [matchId: BigNumberish, agentId1: BigNumberish, agentId2: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        totalPool: bigint;
        agent1Pool: bigint;
        agent2Pool: bigint;
        winningAgentId: bigint;
        settled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserBet"
  ): TypedContractMethod<
    [matchId: BigNumberish, agentId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserBets"
  ): TypedContractMethod<
    [
      matchId: BigNumberish,
      user: AddressLike,
      agentId1: BigNumberish,
      agentId2: BigNumberish
    ],
    [[bigint, bigint] & { betOn1: bigint; betOn2: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "matchTotalPool"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "matchWinner"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [matchId: BigNumberish, onAgentId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleAvABets"
  ): TypedContractMethod<
    [matchId: BigNumberish, winningAgentId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userBets"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [bigint],
    "view"
  >;

  getEvent(
    key: "AvABetsSettled"
  ): TypedContractEvent<
    AvABetsSettledEvent.InputTuple,
    AvABetsSettledEvent.OutputTuple,
    AvABetsSettledEvent.OutputObject
  >;
  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;

  filters: {
    "AvABetsSettled(uint256,uint256,uint256)": TypedContractEvent<
      AvABetsSettledEvent.InputTuple,
      AvABetsSettledEvent.OutputTuple,
      AvABetsSettledEvent.OutputObject
    >;
    AvABetsSettled: TypedContractEvent<
      AvABetsSettledEvent.InputTuple,
      AvABetsSettledEvent.OutputTuple,
      AvABetsSettledEvent.OutputObject
    >;

    "BetPlaced(uint256,uint256,address,uint256)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
  };
}
