/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAvABettingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ava_getGameServer"
      | "ava_getSaltToken"
      | "ava_setGameServer"
      | "ava_setSaltToken"
      | "betPools"
      | "betsSettled"
      | "claimWinnings"
      | "getAvABettingInfo"
      | "getUserBet"
      | "getUserBets"
      | "matchWinner"
      | "placeBet"
      | "settleAvABets"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ava_getGameServer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ava_getSaltToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ava_setGameServer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ava_setSaltToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "betPools",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "betsSettled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimWinnings",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAvABettingInfo",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBet",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBets",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "matchWinner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleAvABets",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ava_getGameServer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ava_getSaltToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ava_setGameServer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ava_setSaltToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "betPools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "betsSettled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvABettingInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUserBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settleAvABets",
    data: BytesLike
  ): Result;
}

export interface IAvABetting extends BaseContract {
  connect(runner?: ContractRunner | null): IAvABetting;
  waitForDeployment(): Promise<this>;

  interface: IAvABettingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ava_getGameServer: TypedContractMethod<[], [string], "view">;

  ava_getSaltToken: TypedContractMethod<[], [string], "view">;

  ava_setGameServer: TypedContractMethod<
    [_gameServer: AddressLike],
    [void],
    "nonpayable"
  >;

  ava_setSaltToken: TypedContractMethod<
    [_salt: AddressLike],
    [void],
    "nonpayable"
  >;

  betPools: TypedContractMethod<
    [matchId: BigNumberish, agentId: BigNumberish],
    [bigint],
    "view"
  >;

  betsSettled: TypedContractMethod<[matchId: BigNumberish], [boolean], "view">;

  claimWinnings: TypedContractMethod<
    [matchId: BigNumberish, winningAgentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAvABettingInfo: TypedContractMethod<
    [matchId: BigNumberish, agentId1: BigNumberish, agentId2: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        totalPool: bigint;
        agent1Pool: bigint;
        agent2Pool: bigint;
        winningAgentId: bigint;
        settled: boolean;
      }
    ],
    "view"
  >;

  getUserBet: TypedContractMethod<
    [matchId: BigNumberish, agentId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  getUserBets: TypedContractMethod<
    [
      matchId: BigNumberish,
      user: AddressLike,
      agentId1: BigNumberish,
      agentId2: BigNumberish
    ],
    [[bigint, bigint] & { betOn1: bigint; betOn2: bigint }],
    "view"
  >;

  matchWinner: TypedContractMethod<[matchId: BigNumberish], [bigint], "view">;

  placeBet: TypedContractMethod<
    [matchId: BigNumberish, onAgentId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  settleAvABets: TypedContractMethod<
    [matchId: BigNumberish, winningAgentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ava_getGameServer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ava_getSaltToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ava_setGameServer"
  ): TypedContractMethod<[_gameServer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ava_setSaltToken"
  ): TypedContractMethod<[_salt: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "betPools"
  ): TypedContractMethod<
    [matchId: BigNumberish, agentId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "betsSettled"
  ): TypedContractMethod<[matchId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "claimWinnings"
  ): TypedContractMethod<
    [matchId: BigNumberish, winningAgentId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAvABettingInfo"
  ): TypedContractMethod<
    [matchId: BigNumberish, agentId1: BigNumberish, agentId2: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        totalPool: bigint;
        agent1Pool: bigint;
        agent2Pool: bigint;
        winningAgentId: bigint;
        settled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserBet"
  ): TypedContractMethod<
    [matchId: BigNumberish, agentId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserBets"
  ): TypedContractMethod<
    [
      matchId: BigNumberish,
      user: AddressLike,
      agentId1: BigNumberish,
      agentId2: BigNumberish
    ],
    [[bigint, bigint] & { betOn1: bigint; betOn2: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "matchWinner"
  ): TypedContractMethod<[matchId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [matchId: BigNumberish, onAgentId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleAvABets"
  ): TypedContractMethod<
    [matchId: BigNumberish, winningAgentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
