/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface BridgeFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bridgeIn"
      | "bridgeInWithSignature"
      | "bridgeOut"
      | "bridge_addRelayer"
      | "bridge_addSupportedChain"
      | "bridge_feeDistributor"
      | "bridge_initialize"
      | "bridge_isChainSupported"
      | "bridge_isRelayer"
      | "bridge_removeRelayer"
      | "bridge_removeSupportedChain"
      | "bridge_setBridgeFeeBps"
      | "bridge_setFeeDistributor"
      | "bridge_setTrustedSigners"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BridgeFeeUpdated"
      | "BridgeIn"
      | "BridgeOut"
      | "ChainSupported"
      | "RelayerUpdated"
      | "TrustedSignerUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bridgeIn",
    values: [BigNumberish, BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeInWithSignature",
    values: [
      BigNumberish,
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeOut",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bridge_addRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bridge_addSupportedChain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bridge_feeDistributor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bridge_initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bridge_isChainSupported",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bridge_isRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bridge_removeRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bridge_removeSupportedChain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bridge_setBridgeFeeBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bridge_setFeeDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bridge_setTrustedSigners",
    values: [AddressLike[], BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "bridgeIn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bridgeInWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bridgeOut", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bridge_addRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridge_addSupportedChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridge_feeDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridge_initialize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridge_isChainSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridge_isRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridge_removeRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridge_removeSupportedChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridge_setBridgeFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridge_setFeeDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridge_setTrustedSigners",
    data: BytesLike
  ): Result;
}

export namespace BridgeFeeUpdatedEvent {
  export type InputTuple = [feeBps: BigNumberish];
  export type OutputTuple = [feeBps: bigint];
  export interface OutputObject {
    feeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BridgeInEvent {
  export type InputTuple = [
    fromChain: BigNumberish,
    sender: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    fromChain: bigint,
    sender: string,
    recipient: string,
    amount: bigint,
    nonce: bigint
  ];
  export interface OutputObject {
    fromChain: bigint;
    sender: string;
    recipient: string;
    amount: bigint;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BridgeOutEvent {
  export type InputTuple = [
    toChain: BigNumberish,
    sender: AddressLike,
    recipient: BytesLike,
    amount: BigNumberish,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    toChain: bigint,
    sender: string,
    recipient: string,
    amount: bigint,
    nonce: bigint
  ];
  export interface OutputObject {
    toChain: bigint;
    sender: string;
    recipient: string;
    amount: bigint;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChainSupportedEvent {
  export type InputTuple = [chainId: BigNumberish, supported: boolean];
  export type OutputTuple = [chainId: bigint, supported: boolean];
  export interface OutputObject {
    chainId: bigint;
    supported: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerUpdatedEvent {
  export type InputTuple = [relayer: AddressLike, isRelayer: boolean];
  export type OutputTuple = [relayer: string, isRelayer: boolean];
  export interface OutputObject {
    relayer: string;
    isRelayer: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrustedSignerUpdatedEvent {
  export type InputTuple = [signer: AddressLike];
  export type OutputTuple = [signer: string];
  export interface OutputObject {
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BridgeFacet extends BaseContract {
  connect(runner?: ContractRunner | null): BridgeFacet;
  waitForDeployment(): Promise<this>;

  interface: BridgeFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bridgeIn: TypedContractMethod<
    [
      fromChain: BigNumberish,
      sender: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      nonce: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  bridgeInWithSignature: TypedContractMethod<
    [
      fromChain: BigNumberish,
      sender: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      nonce: BigNumberish,
      signatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  bridgeOut: TypedContractMethod<
    [toChain: BigNumberish, recipient: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  bridge_addRelayer: TypedContractMethod<
    [relayer: AddressLike],
    [void],
    "nonpayable"
  >;

  bridge_addSupportedChain: TypedContractMethod<
    [chainId: BigNumberish],
    [void],
    "nonpayable"
  >;

  bridge_feeDistributor: TypedContractMethod<[], [string], "view">;

  bridge_initialize: TypedContractMethod<[], [void], "nonpayable">;

  bridge_isChainSupported: TypedContractMethod<
    [chainId: BigNumberish],
    [boolean],
    "view"
  >;

  bridge_isRelayer: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  bridge_removeRelayer: TypedContractMethod<
    [relayer: AddressLike],
    [void],
    "nonpayable"
  >;

  bridge_removeSupportedChain: TypedContractMethod<
    [chainId: BigNumberish],
    [void],
    "nonpayable"
  >;

  bridge_setBridgeFeeBps: TypedContractMethod<
    [feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  bridge_setFeeDistributor: TypedContractMethod<
    [_distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  bridge_setTrustedSigners: TypedContractMethod<
    [signers: AddressLike[], minSigs: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bridgeIn"
  ): TypedContractMethod<
    [
      fromChain: BigNumberish,
      sender: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      nonce: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bridgeInWithSignature"
  ): TypedContractMethod<
    [
      fromChain: BigNumberish,
      sender: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      nonce: BigNumberish,
      signatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bridgeOut"
  ): TypedContractMethod<
    [toChain: BigNumberish, recipient: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bridge_addRelayer"
  ): TypedContractMethod<[relayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bridge_addSupportedChain"
  ): TypedContractMethod<[chainId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bridge_feeDistributor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bridge_initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bridge_isChainSupported"
  ): TypedContractMethod<[chainId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "bridge_isRelayer"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "bridge_removeRelayer"
  ): TypedContractMethod<[relayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bridge_removeSupportedChain"
  ): TypedContractMethod<[chainId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bridge_setBridgeFeeBps"
  ): TypedContractMethod<[feeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bridge_setFeeDistributor"
  ): TypedContractMethod<[_distributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bridge_setTrustedSigners"
  ): TypedContractMethod<
    [signers: AddressLike[], minSigs: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BridgeFeeUpdated"
  ): TypedContractEvent<
    BridgeFeeUpdatedEvent.InputTuple,
    BridgeFeeUpdatedEvent.OutputTuple,
    BridgeFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BridgeIn"
  ): TypedContractEvent<
    BridgeInEvent.InputTuple,
    BridgeInEvent.OutputTuple,
    BridgeInEvent.OutputObject
  >;
  getEvent(
    key: "BridgeOut"
  ): TypedContractEvent<
    BridgeOutEvent.InputTuple,
    BridgeOutEvent.OutputTuple,
    BridgeOutEvent.OutputObject
  >;
  getEvent(
    key: "ChainSupported"
  ): TypedContractEvent<
    ChainSupportedEvent.InputTuple,
    ChainSupportedEvent.OutputTuple,
    ChainSupportedEvent.OutputObject
  >;
  getEvent(
    key: "RelayerUpdated"
  ): TypedContractEvent<
    RelayerUpdatedEvent.InputTuple,
    RelayerUpdatedEvent.OutputTuple,
    RelayerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TrustedSignerUpdated"
  ): TypedContractEvent<
    TrustedSignerUpdatedEvent.InputTuple,
    TrustedSignerUpdatedEvent.OutputTuple,
    TrustedSignerUpdatedEvent.OutputObject
  >;

  filters: {
    "BridgeFeeUpdated(uint256)": TypedContractEvent<
      BridgeFeeUpdatedEvent.InputTuple,
      BridgeFeeUpdatedEvent.OutputTuple,
      BridgeFeeUpdatedEvent.OutputObject
    >;
    BridgeFeeUpdated: TypedContractEvent<
      BridgeFeeUpdatedEvent.InputTuple,
      BridgeFeeUpdatedEvent.OutputTuple,
      BridgeFeeUpdatedEvent.OutputObject
    >;

    "BridgeIn(uint256,bytes,address,uint256,uint256)": TypedContractEvent<
      BridgeInEvent.InputTuple,
      BridgeInEvent.OutputTuple,
      BridgeInEvent.OutputObject
    >;
    BridgeIn: TypedContractEvent<
      BridgeInEvent.InputTuple,
      BridgeInEvent.OutputTuple,
      BridgeInEvent.OutputObject
    >;

    "BridgeOut(uint256,address,bytes,uint256,uint256)": TypedContractEvent<
      BridgeOutEvent.InputTuple,
      BridgeOutEvent.OutputTuple,
      BridgeOutEvent.OutputObject
    >;
    BridgeOut: TypedContractEvent<
      BridgeOutEvent.InputTuple,
      BridgeOutEvent.OutputTuple,
      BridgeOutEvent.OutputObject
    >;

    "ChainSupported(uint256,bool)": TypedContractEvent<
      ChainSupportedEvent.InputTuple,
      ChainSupportedEvent.OutputTuple,
      ChainSupportedEvent.OutputObject
    >;
    ChainSupported: TypedContractEvent<
      ChainSupportedEvent.InputTuple,
      ChainSupportedEvent.OutputTuple,
      ChainSupportedEvent.OutputObject
    >;

    "RelayerUpdated(address,bool)": TypedContractEvent<
      RelayerUpdatedEvent.InputTuple,
      RelayerUpdatedEvent.OutputTuple,
      RelayerUpdatedEvent.OutputObject
    >;
    RelayerUpdated: TypedContractEvent<
      RelayerUpdatedEvent.InputTuple,
      RelayerUpdatedEvent.OutputTuple,
      RelayerUpdatedEvent.OutputObject
    >;

    "TrustedSignerUpdated(address)": TypedContractEvent<
      TrustedSignerUpdatedEvent.InputTuple,
      TrustedSignerUpdatedEvent.OutputTuple,
      TrustedSignerUpdatedEvent.OutputObject
    >;
    TrustedSignerUpdated: TypedContractEvent<
      TrustedSignerUpdatedEvent.InputTuple,
      TrustedSignerUpdatedEvent.OutputTuple,
      TrustedSignerUpdatedEvent.OutputObject
    >;
  };
}
