/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AgentIdentityFacet__factory } from "./AgentIdentityFacet__factory";
export { IAgentIdentity__factory } from "./IAgentIdentity__factory";
